### ISSUE TITLE
webclient without build,cannot be used

### ISSUE THREAD

**Issue by kangkanggogithub** [aistream69/aistream#1]
webclient without build,cannot be used

**Comment by aistream69** [comment]
please visit the README under webclient, it shows how to build webclient using npm.
the demo webclient url(http://124.222.53.156:8080/aistream) is in my develop machine, it is not always live, sorry.

**Comment by kangkanggogithub** [comment]
the demo webclient url(http://124.222.53.156:8080/aistream) can be accessed,but default username(admin) and default password(123456) is error.

**Comment by aistream69** [comment]
yes, most of time i use the machine for developping, and the aistream backend server will be closed.

**Comment by kangkanggogithub** [comment]
OK,when I use "npm run dev" to build webclient,the "Error: Cannot find module aistream/work/webclient/build/dev-server.js" occurred.

**Comment by aistream69** [comment]
same with https://github.com/aistream69/aistream/issues/3, closed.
