### ISSUE TITLE
webclient compile error

### ISSUE THREAD

**Issue by SunL1GHT** [aistream69/aistream#3]
Hello. When I compile  the webclient, the `build/dev-server.js` file cannot be found when execute `npm run dev`.

The error message is as follows：

![image](https://github.com/aistream69/aistream/assets/24656147/07c19f69-08cf-4755-956c-eeee134c83a3)

npm run dev in package.json is as follow：

```json
"scripts": {
  "dev": "cross-env NODE_ENV=online node build/dev-server.js",
  "local": "cross-env NODE_ENV=local node build/dev-server.js",
  "build": "node build/build.js",
  "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
  "e2e": "node test/e2e/runner.js",
  "test": "npm run unit && npm run e2e",
  "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
}
```

**Comment by SunL1GHT** [comment]
Could you provide the files in the build directory? Thank you very much.

**Comment by aistream69** [comment]
> Could you provide the files in the build directory? Thank you very much.

Sorry, the key "build" is in my .gitignore, i have uploaded it just now, please try to git pull again.
PS : Webclient is not the necessary module in this repo, and the orig version is https://github.com/bailicangdu/vue2-manage.
Best Regards.
